namespace: "mateothegreat"
name: "aws_vpc_create"
version: "0.0.1"
readme: "README.md"
authors:
  - "Matthew Davis (https://matthewdavis.io)"
description: "Prometheus exports pusher."
license: ["MIT"]
license_file: "COPYING"
tags: ["cloud", "aws", "vpc"]
repository: "https://github.com/mateothegreat/prometheus-exporter-pusher.git"
homepage: "https://github.com/mateothegreat/prometheus-exporter-pusher"
issues: "https://github.com/mateothegreat/prometheus-exporter-pusher/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc"
